[FE] 야구 필드 애니메이션 적용
codesquad-member-2020/baseball-09 pull request #39
Opened 2020-05-08 07:40 UTC by choisohyun

### 구현한 내용

- Pitch 버튼 클릭할 때마다 1루씩 이동하도록 keyframe 구현

![captured](https://user-images.githubusercontent.com/30427711/81383179-90225d00-914a-11ea-9ecd-b583c669830b.gif)

Close #34

2020-05-08 12:11 UTC, sangwon21 requested changes

2020-05-08 12:11 UTC, sangwon21 commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
> +      <HitterWrap active={Hits[hit]}>
HitterWrap 보다 Hitter가 더 적절할 것 같은데 어떻게 생각하나요? 만약 동의하신다면, 밑에 Hitter는 변경하셔야겠죠? 이 부분을 아예 Hitter 컴포넌트로 분리하는 것도 괜찮은 방법일지도...

2020-05-08 12:11 UTC, sangwon21 commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
> +    if (hit + 1 === 4) setHit(-1);
typescript의 enum을 활용하면, 여기에 쓰인 매직 넘버를 없앨 수 있지 않을까요?

2020-05-08 12:11 UTC, sangwon21 commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
> +import styled, { keyframes, Keyframes, css } from "styled-components";
keyframes와 Keyframes는 무엇이 다른가요?

2020-05-08 12:11 UTC, sangwon21 commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
>  import PitcherImg from "./fitcher.png";
fitcher가 아니라 pitcher가 되야될 듯...

2020-05-08 12:15 UTC, sangwon21 requested changes

2020-05-08 12:15 UTC, sangwon21 commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
> +const Hits = [FirstHit, SecondHit, ThirdHit, FourthHit];
Hit이라는 단어보다는 Bases 라는 단어가 더 적절해 보이는데 어떻게 생각하시나요?

2020-05-08 12:15 UTC, sangwon21 commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
> +const FirstHit = keyframes`
hit 보다는 base가 더 적절해 보이는 데, 어떻게 생각하시나요?

2020-05-08 17:04 UTC, choisohyun commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
> +import styled, { keyframes, Keyframes, css } from "styled-components";
styled component에서 keyframes는 스타일 값을 지정하는데 쓰고 Keyframe은 타입으로 쓰입니다

2020-05-08 17:05 UTC, choisohyun commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
>  import PitcherImg from "./fitcher.png";
수정했습니다...

2020-05-08 17:11 UTC, choisohyun commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
> +const FirstHit = keyframes`
base가 의미가 더 사는것같네요. 변경했습니다

2020-05-08 17:24 UTC, choisohyun commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
> +    if (hit + 1 === 4) setHit(-1);
enum이 익숙하지가 않아 안떠올랐네요 추가해봤습니다 👍

2020-05-08 18:09 UTC, choisohyun commented on FE/src/components/GamePage/BaseballField/Field/Field.tsx
> +      <HitterWrap active={Hits[hit]}>
Hitter는 다시 보니 없어도 되는 태그여서 정리 후 삭제하고, HitterWrap을 Hitter로 변경했습니다. 
컴포넌트 분리는 enum으로 하면 타입오류가 나서 내일 더 시도해 볼게요..

2020-05-09 01:44 UTC, choisohyun commented
컴포넌트 분리까지 리뷰 사항 반영했어요 ~! 확인부탁드려요 @sangwon21

2020-05-11 05:14 UTC, merged